### ISSUE TITLE
Default build generates new files in the git repository

### ISSUE THREAD

**Issue by opcoach** [eclipse/ecf#120]
Regarding the eclipse-platform contributor journey as described in this issue : [ide-wg/issue47_Note2617895](https://gitlab.eclipse.org/eclipse-wg/ide-wg/community/-/issues/47#note_2617895), the ECF project has a default build producing new files in the git repository.

This is confusing, because when we create an Eclipse IDE to fix bugs, we directly get these files modified (sorry the shell is in French) : 

![image](https://github.com/user-attachments/assets/b5f58426-5e18-445b-aae0-91cc44476de3)

It seems that some services have been generated and added in the MANIFEST : 

![image](https://github.com/user-attachments/assets/d3386b64-98d1-46f7-a63b-05cde9500412)

They should be directly committed

**Comment by scottslewis** [comment]
Fixed...along with some other housekeeping.

New integration build is available here:   https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.15.2.v20240808-2136/

Please communicate this to Ed or whomever is currently updating the platform build.
