### ISSUE TITLE
Missing component definition for `org.eclipse.ecf.osgi.services.remoteserviceadmin.console` 1.31

### ISSUE THREAD

**Issue by salvatore-coppola** [eclipse/ecf#127]
Hi,
in the latest available version (1.31) of the bundle `org.eclipse.ecf.osgi.services.remoteserviceadmin.console`  the xml component definition file is missing.
This causes RSACommand.xml to fail to load.
The xml descriptor is present in the build of the previous artifact 1.30 that works without problems.

**Comment by scottslewis** [comment]
Thanks for the report.  I believe I've already fixed this in source/build, would you please verify with this build:

https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.15.2.v20240812-1535/

I'm planning a 3.15.2 release for later this week.

**Comment by salvatore-coppola** [comment]
Now everything seems fine
