### ISSUE TITLE
The version of org.eclipse.ecf.provider.filetransfer.httpclientjava has been updated to a smaller version:

### ISSUE THREAD

**Issue by merks** [eclipse/ecf#142]
This looks wrong:

https://github.com/eclipse/ecf/blob/06d6e4a1b9b1f3712a400faefc4b9d64e6de3bb0/providers/bundles/org.eclipse.ecf.provider.filetransfer.httpclientjava/META-INF/MANIFEST.MF#L5

This commit back-leveled the version

https://github.com/eclipse/ecf/commit/99562dbe92b0cf6b0fb6893755386f1e4ae5340a

These versions are available in p2 repositories:

![image](https://github.com/user-attachments/assets/e9f65e69-8225-45c1-87fe-0aa11d007362)

**Comment by scottslewis** [comment]
Corrected to 2.1.0 (minor segment incremented).  Available now at:  https://download.eclipse.org/rt/ecf/snapshot

**Comment by scottslewis** [comment]
closing

**Comment by merks** [comment]
Thanks. 🙏
