### ISSUE TITLE
Upgrade to JavaSE-17

### ISSUE THREAD

**Issue by jukzi** [eclipse/ecf#33]
Since Java runtime systems are not compatible to each other anymore i ask to upgrade to a recent version.
The Eclipse IDE moved it's Bundle-RequiredExecutionEnvironment to JavaSE-17. Since eclipse platform depends on ecf, i request to update ecf too.
May i suggest a PR?

**Comment by scottslewis** [comment]
Thanks.   It's going to be a few days before I can produce another build for platform to consume, as ECF has a couple of other pending issues to include:  i.e. issue #27 and issue #26
