### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by merks** [eclipse/ecf#40]
I updated your contribution to SimRel to match what is consumed by the platform:

https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/202055

Analyzing duplicates in SimRel I noticed ECF is  using quite an old version of ASM compared to the version used by everyone else:

![image](https://github.com/eclipse/ecf/assets/208716/f5a502ef-16b1-40c5-978a-689c1f753a91)

I'd update the target platform for you, but I'm not sure which one:

![image](https://github.com/eclipse/ecf/assets/208716/8e316066-fec7-47f1-82de-186af4b87e68)

A bunch of them seem to be getting changed in the last while:

![image](https://github.com/eclipse/ecf/assets/208716/5ff24892-5c49-468a-bdd4-0100b0e43789)

I'm not sure why you explicitly list source bundles when you already have `includeSource="true"` on the location...

The versions of ASM change quite regularly.  Currently it's at 9.5.0.  The platform is getting it direct from Maven:
```
	  <location includeDependencyDepth="none" includeDependencyScopes="compile" includeSource="true" label="ASM" missingManifest="error" type="Maven">
		  <dependencies>
			  <dependency>
				  <groupId>org.ow2.asm</groupId>
				  <artifactId>asm-commons</artifactId>
				  <version>9.5</version>
				  <type>jar</type>
			  </dependency>
			  <dependency>
				  <groupId>org.ow2.asm</groupId>
				  <artifactId>asm-util</artifactId>
				  <version>9.5</version>
				  <type>jar</type>
			  </dependency>
			  <dependency>
				  <groupId>org.ow2.asm</groupId>
				  <artifactId>asm</artifactId>
				  <version>9.5</version>
				  <type>jar</type>
			  </dependency>
			  <dependency>
				  <groupId>org.ow2.asm</groupId>
				  <artifactId>asm-tree</artifactId>
				  <version>9.5</version>
				  <type>jar</type>
			  </dependency>
			  <dependency>
				  <groupId>org.ow2.asm</groupId>
				  <artifactId>asm-analysis</artifactId>
				  <version>9.5</version>
				  <type>jar</type>
			  </dependency>
		  </dependencies>
	  </location>
```
And I've been helpful update the version as new versions become available.  If you consume directly, you will need to PGP sign the artifacts.  You can also get these versions from here where they are already PGP signed:

https://download.eclipse.org/oomph/simrel-maven/

E.g.,  from here:

https://download.eclipse.org/oomph/simrel-maven/2023-06

How best can I help to get  this version updated?

Note that this would be less of a concern if you did **not** include this bundle in your feature(s).  All the bundles actually allow asm up to version 10.  Only the feature specifically requires the older version:

![image](https://github.com/eclipse/ecf/assets/208716/802f7bd2-9ecf-4133-b925-9deb12081654)

If we eliminated the include, then I won't be bugging you again until version 10 comes out...

Again, please let me know how best I can help.

**Comment by scottslewis** [comment]
Hi Ed,

Thanks.   I'll fix/remove asm 9 from feature this coming weekend when I 
return from time off.

Scott

**Comment by scottslewis** [comment]
Hi @merks 

It turns out that ECF has some non-eclipse consumers that use the rosgi distribution provider, and this provider (written long ago by other ECF committer) depends upon ASM core bundle.   So to make it easier for those consumers, we include the ASM core bundle in the ECF repo.

I've updated the target platform (thanks for the simrel repo links above) and built/deployed ECF version 3.14.39.  The repo is here:

http://download.eclipse.org/rt/ecf/3.14.39/site.p2

I tried to update the simrel entry for ECF, but something was wrong with my auth/access/gerrit config.  Would you please update the simrel entry ecf.aggrcon?  Here's the new content for 3.14.39

<?xml version="1.0" encoding="ASCII"?>
<aggregator:Contribution xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:aggregator="http://www.eclipse.org/cbi/p2repo/2011/aggregator/1.1.0" label="ECF">
  <repositories location="https://download.eclipse.org/rt/ecf/3.14.39/site.p2/3.14.39.v20230529-2152" description="ECF updates">
    <features name="org.eclipse.ecf.core.feature.group" versionRange="[3.14.39.v20230529-2152]">
      <categories href="simrel.aggr#//@customCategories[identifier='Collaboration']"/>
      <categories href="simrel.aggr#//@customCategories[identifier='EclipseRT%20Target%20Platform%20Components']"/>
    </features>
    <features name="org.eclipse.ecf.core.source.feature.group" versionRange="[3.14.39.v20230529-2152]">
      <categories href="simrel.aggr#//@customCategories[identifier='Collaboration']"/>
      <categories href="simrel.aggr#//@customCategories[identifier='EclipseRT%20Target%20Platform%20Components']"/>
    </features>
    <features name="org.eclipse.ecf.remoteservice.sdk.feature.feature.group" versionRange="[3.14.39.v20230529-2049]">
      <categories href="simrel.aggr#//@customCategories[identifier='Collaboration']"/>
      <categories href="simrel.aggr#//@customCategories[identifier='EclipseRT%20Target%20Platform%20Components']"/>
    </features>
    <features name="org.eclipse.ecf.remoteservice.sdk.feature.source.feature.group" versionRange="[3.14.39.v20230529-2049]">
      <categories href="simrel.aggr#//@customCategories[identifier='Collaboration']"/>
      <categories href="simrel.aggr#//@customCategories[identifier='EclipseRT%20Target%20Platform%20Components']"/>
    </features>
  </repositories>
  <contacts href="simrel.aggr#//@contacts[email='slewis@composent.com']"/>
</aggregator:Contribution>

Thanks very much Ed.  It's appreciated.   Also...if there is up-to-date info for committing changes to simrel these days (via gerrit I assume) please point me at them and I'll update.

**Comment by merks** [comment]
I've made the following change to SimRel:

https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/202176

There was a long thread about other people who had problems committing, perhaps you have the same issue:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3053#note_1107917

Or perhaps you need a fresh installation with the latest tools which you can create automatically:

https://www.eclipse.org/setups/installer/?url=https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/interim/SimultaneousReleaseTrainConfiguration.setup&show=true

Note that what I've done in a bunch of other projects is either of the following:

- Create a "dependencies" feature that is not installed by the user, is included only in the category.xml categorized, and then move 3rd prty bundle includes to that feature.
- Mention the bundles directly in the category.xml.

Either way, the bundles will then end up in the update site as before but then installing a feature does not lock in a particular version, though there is a version available so that all the bundles of the feature can be installed.

Thanks for addressing the issue!
