### ISSUE TITLE
The Require-Capability of com.mycorp.examples.timeservice.consumer.filediscovery is syntactically incorrect

### ISSUE THREAD

**Issue by merks** [eclipse/ecf#67]
The first filter value in this example requires quotes because the value contains the `=` character:

https://github.com/eclipse/ecf/blob/9264db2cd9569684ec3434e2341f13b08e0e278e/examples/bundles/com.mycorp.examples.timeservice.consumer.filediscovery/META-INF/MANIFEST.MF#L10-L11

See this for background details:

- https://github.com/bndtools/bnd/issues/5762
- https://github.com/merks/simrel-maven/issues/10

**Comment by scottslewis** [comment]
Fixed with pr https://github.com/eclipse/ecf/pull/68
