### ISSUE TITLE
Provide traceablity when moving a project

### ISSUE THREAD

**Issue by rolfth** [eclipse/ecf#7]
Today I just had a failing git pull from ECF. I had to manually analyze this problem to find out that the git repository got renamed:
https://git.eclipse.org/c/ecf/org.eclipse.ecf.git.deletemeafter043022/

No clue what happened there, just because some projects are moving, went to check the website. After some dead links found the project here.

Please consider the users that not following the project closely when moving. As a community there should be some best practices.
e.g. for https://git.eclipse.org/c/platform/eclipse.platform.releng.git it is quite obvious where the project went.

**Comment by scottslewis** [comment]
I've opened this issue https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3423   with the foundation.  Thanks for the report.
