### ISSUE TITLE
Host an ECF Setup?

### ISSUE THREAD

**Issue by merks** [eclipse/ecf#79]
For my most recent contribution to ECF, I authored an Oomph setup for ECF.  It can be used in a *.md as below.  Note that the button is a link and has hover help.  Try to open the link in a separate page to see what the helpful documentation page looks like.

##
## Creating an Eclipse Development Environment

You can set up a pre-configured IDE for the development of the Eclipse Communications Framework using the following link:

[![Create Eclipse Development Environment for ECF](https://download.eclipse.org/oomph/www/setups/svg/ECF.svg)](https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse/ecf/master/releng/org.eclipse.ecf.releng/ECFConfiguration.setup&show=true "Click to open Eclipse-Installer Auto Launch or drag onto your running installer's title area")

##
Here's an analogous example of the usage:

https://github.com/eclipse-emf/org.eclipse.emf/blob/master/CONTRIBUTING.md#creating-an-eclipse-development-environment
##

It creates a workspace with all the (valid) projects like this:

![image](https://github.com/eclipse/ecf/assets/208716/4c1e05db-0c25-436a-aad1-2599d7b9b78e)

The setup files  are currently hosted by Oomph's Git repository but it's generally better for a project to host its own setup so that you can edit it yourself in the future.  Of course I'm happy to help you with any changes you would like in the future.

If you are interested, I can create a PR to contribute this.

I can describe in more detail what the setup is doing, but that only makes sense if you wish to make use of this.  (For example, it is using Oomph's Targlets to generate a target platform, which is generally much easier than authoring such things by hand because you generally only have to provide a list of update sites and the dependencies of your projects specify what's needed from those sites.)

**Comment by scottslewis** [comment]
Hi Ed.   Yes sure I'm interested.  Thanks.

**Comment by merks** [comment]
I'll create a PR tomorrow then.

**Comment by merks** [comment]
All done.  🎉
