### ISSUE TITLE
merge gerrit changes into github repo

### ISSUE THREAD

**Issue by scottslewis** [eclipse/ecf#8]
On this issue:   https://bugs.eclipse.org/bugs/show_bug.cgi?id=578940   there were changes applied via gerrit process to ECF repo after the switch to github.com/eclipse/ecf repo.   

These changes need to be merged in from the old repo to the github repo.   Is there an automated process for doing that?   

In general, since the platform (as consumer of ECF) is used to using gerrit for providing changes to ECF is there a way to have gerrit changes end up here (in github repo)?   Or do we have to request them to open github prs instead of gerrit?   Thanks.

**Comment by wimjongman** [comment]
Sorry I missed this. I get so many eclipse mails that the bulk is moved to a special folder. If you need my attention then please mention me with @wimjongman 

Yes, there must be a procedure for it. We should be able to check out a Gerrit change and then push it to a PR or push it to a branch on a fork.

Let me work on this for a bit.

**Comment by scottslewis** [comment]
thanks Wim.
