### ISSUE TITLE
Missing artifact update from maven central

### ISSUE THREAD

**Issue by amergey** [eclipse/ecf#86]
some artifacts update (5.1.103) have not been published in maven central 
For example org.eclipse.ecf.filetransfer and org.eclipse.ecf.discovery
![image](https://github.com/eclipse/ecf/assets/956840/18e891be-0aaa-4d18-847a-1bd9b85213ee)

**Comment by scottslewis** [comment]
Thanks for the report.   I simply forgot to promote/release the maven repo to maven central using the https://oss.sonatype.org console.   I've just done so and so in the next few hours the missing bundles should appear at maven central.  If they do not, feel free to reopen.
